# Generated by Django 3.2.23 on 2024-02-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=20)),
                ('movie_desc', models.CharField(max_length=150)),
                ('movie_status', models.BooleanField(default=True)),
                ('avr_rating', models.FloatField(default=0)),
                ('total_ratings', models.IntegerField(default=0)),
                ('movie_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
