# Generated by Django 3.2.23 on 2024-02-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sort', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_created',
            field=models.IntegerField(),
        ),
    ]
