# Generated by Django 3.2.23 on 2024-02-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sort', '0002_alter_movie_movie_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saved_Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved', models.URLField()),
            ],
        ),
    ]
