# Generated by Django 3.2.23 on 2024-02-05 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sort', '0004_saved_search_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Saved_Search',
        ),
    ]
