# Generated by Django 3.2.23 on 2024-02-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('job_type', models.CharField(max_length=30)),
                ('opening_slots', models.IntegerField()),
                ('location', models.CharField(max_length=30)),
                ('include_freshers', models.BooleanField(default=False)),
            ],
        ),
    ]
