# Generated by Django 3.2.23 on 2024-02-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='phone_number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
