# Generated by Django 3.2.23 on 2024-02-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_model', '0002_alter_customeruser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
