# Generated by Django 3.2.23 on 2024-02-09 08:13

from django.db import migrations, models
import user_model.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_model', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=user_model.models.avatar),
        ),
    ]
